sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stevorc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stevorc/react-test npm test -- --coverage

after_success:
  - docker build -t geksdk01/multi-client ./client
  - docker build -t geksdk01/multi-nginx ./nginx
  - docker build -t geksdk01/multi-api ./server
  - docker build -t geksdk01/multi-worker ./worker
  # Log to the docker HUB
  #Cette commande va lire le psw et va la passer via pipe à la en stdin de la 2eme commande
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the image and push to the docker HUB
  - docker push geksdk01/multi-client
  - docker push geksdk01/multi-nginx
  - docker push geksdk01/multi-api
  - docker push geksdk01/multi-worker